### ISSUE TITLE
Bố cục

### ISSUE THREAD

**Issue by nntruyen027** [QBitGenZ/lv003-frontend-admin#18]
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/89064690/7e9067f7-ea62-40ad-8323-97d8f215f9f1)
Bố cục cần chỉnh sửa lại cho cân đối

**Comment by trandinhnghiem2014676** [comment]
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/125441730/f502086d-ab76-483f-bd1a-1bda71f9c390)
Lỗi bố cục không gian trong  đơn hàng

**Comment by nntruyen027** [comment]
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/89064690/9f61c24b-c774-4ea1-a5e5-c5dad8ef84da)
Sao không ngay giữa

**Comment by trandinhnghiem2014676** [comment]
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/125441730/29e69908-edff-479c-9570-04da22ff8379)
Số lượng sản phẩm trên một hàng quá nhiều dẫn đến chật trội
