### ISSUE TITLE
Lỗi thêm sửa xóa

### ISSUE THREAD

**Issue by nntruyen027** [QBitGenZ/lv003-frontend-admin#23]

**Comment by nntruyen027** [comment]
Chưa xóa được tài khoản người dùng
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/89064690/c36673f1-44c2-4885-a1c2-345901bc481b)

**Comment by trandinhnghiem2014676** [comment]
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/125441730/1f6043d5-bd17-496d-b21d-067f5e3a15a7)
![image](https://github.com/QBitGenZ/lv003-frontend-admin/assets/125441730/99e0ec09-9505-48af-8046-ad3b8b8dcddf)
Không thể hủy đơn hàng trong danh sách đơn hàng
